// src/lib/components/ChunksComp.tsx
import React from "react";
import type { Chunk } from "../types.ts";
import InlineMath from "./InlineMath.tsx";

interface ChunksCompProps {
  chunks: Chunk[];
  citeKey: string;
}

function ChunksComp({ chunks = [], citeKey }: ChunksCompProps) {
  return (
    <>
      {chunks.map((chunk, i) => {
        const key = `${citeKey}-${i}`;

        if ("Normal" in chunk) {
          return <span key={key}>{chunk.Normal}</span>;
        } else if ("Verbatim" in chunk) {
          return <span key={key}>{chunk.Verbatim}</span>;
        } else if ("Math" in chunk) {
          return <InlineMath key={key} content={chunk.Math} />;
        }

        return null;
      })}
    </>
  );
}

export default ChunksComp;

// src/components/ChunksComp.tsx
import { For } from "solid-js";
import type { Chunk } from "../types.ts";
import InlineMath from "./InlineMath.tsx";

interface ChunksCompProps {
  chunks: Chunk[];
  citeKey: string;
}

function ChunksComp(props: ChunksCompProps) {
  return (
    <>
      <For each={props.chunks || []}>
        {(chunk) => {
          if ("Normal" in chunk) {
            return <span>{chunk.Normal}</span>;
          } else if ("Verbatim" in chunk) {
            return <span>{chunk.Verbatim}</span>;
          } else if ("Math" in chunk) {
            return <InlineMath content={chunk.Math} />;
          }
          return null;
        }}
      </For>
    </>
  );
}

export default ChunksComp;
